# Generated by Django 4.2.13 on 2024-08-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=50)),
                ("price", models.FloatField(default=0.0)),
                ("location", models.CharField(max_length=500)),
                ("contact", models.CharField(max_length=9)),
                ("dob", models.DateField()),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pet_images/{name}/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetBreed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("size", models.IntegerField(default=0)),
                ("lifespan", models.IntegerField(default=0)),
                ("trainability", models.IntegerField(default=0)),
                ("bark", models.IntegerField(default=0)),
                ("energy", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="breed_images/{name}/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=9)),
                ("message", models.TextField()),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adopt.pet"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pet",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adopt.petbreed"
            ),
        ),
    ]
