# Generated by Django 4.2.13 on 2024-08-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="petbreed",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
