# Generated by Django 4.2.13 on 2024-08-25 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adopt", "0002_pet_slug_petbreed_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="owner_name",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AdoptionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_adopt_request", models.BooleanField(default=False)),
                ("adoption_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adoptee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adopt.petcontact",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adopt.pet"
                    ),
                ),
            ],
        ),
    ]
