# Generated by Django 4.2.13 on 2024-08-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adopt", "0003_pet_owner_name_adoptionstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="owner",
        ),
    ]
