# Generated by Django 4.2.9 on 2024-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_image",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
