# Generated by Django 4.2.13 on 2024-06-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="category",
        ),
        migrations.DeleteModel(
            name="volunteer",
        ),
    ]
