# Generated by Django 4.2.13 on 2024-06-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="male",
                        max_length=50,
                    ),
                ),
                ("dob_month", models.IntegerField()),
                ("dob_day", models.IntegerField()),
                ("dob_year", models.IntegerField()),
                ("email", models.EmailField(max_length=200)),
                ("phone", models.CharField(max_length=10)),
                ("full_address", models.TextField()),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("joined_on", models.DateTimeField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_blocked", models.BooleanField(default=False)),
            ],
        ),
    ]
