# Generated by Django 4.2.13 on 2024-06-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0004_volunteer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponser", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=8)),
            ],
        ),
    ]
