# Generated by Django 4.2.13 on 2024-06-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0005_sponser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("time_from", models.TimeField()),
                ("time_to", models.TimeField()),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_banners/"
                    ),
                ),
                ("description", models.TextField()),
                ("venue", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_expired", models.BooleanField(verbose_name=False)),
                ("is_active", models.BooleanField(verbose_name=True)),
                ("is_volunteer_required", models.BooleanField(verbose_name=False)),
                ("volunteers_capacity", models.IntegerField()),
                ("terms", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizers.category",
                    ),
                ),
                (
                    "sponsers",
                    models.ManyToManyField(
                        related_name="events", to="organizers.sponser"
                    ),
                ),
                (
                    "volunteers",
                    models.ManyToManyField(
                        related_name="events", to="organizers.volunteer"
                    ),
                ),
            ],
        ),
    ]
