# Generated by Django 4.2.13 on 2024-06-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0006_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("donated_on", models.DateTimeField(auto_now_add=True)),
                ("if_donated_for_event", models.BooleanField(verbose_name=False)),
                (
                    "donated_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizers.volunteer",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizers.event",
                    ),
                ),
            ],
        ),
    ]
