# Generated by Django 4.2.13 on 2024-06-09 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0007_donation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizers.event",
                    ),
                ),
                (
                    "sponser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizers.sponser",
                    ),
                ),
            ],
        ),
    ]
