# Generated by Django 4.2.13 on 2024-06-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0008_sponsership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="joined_on",
            field=models.BooleanField(default=True),
        ),
    ]
