# Generated by Django 4.2.9 on 2024-06-15 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizers", "0009_alter_volunteer_joined_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="last_name",
        ),
        migrations.AddField(
            model_name="volunteer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
