# Generated by Django 4.2.9 on 2024-07-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizers",
            "0010_remove_volunteer_email_remove_volunteer_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=700, null=True, unique=True),
        ),
    ]
