# Generated by Django 4.2.9 on 2024-07-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0011_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizers.event",
            ),
        ),
    ]
