# Generated by Django 4.2.9 on 2024-07-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0012_alter_donation_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donated_name",
            field=models.CharField(max_length=200),
        ),
    ]
