# Generated by Django 4.2.9 on 2024-07-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0013_alter_donation_donated_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="if_donated_for_event",
            field=models.BooleanField(default=False),
        ),
    ]
