# Generated by Django 4.2.13 on 2024-08-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("pet_violence", "Pet Violence"),
                            ("environmental_violence", "Environmental Violence"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
        ),
    ]
