# Generated by Django 4.2.13 on 2024-09-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recyclerequest",
            name="contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="recyclerequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="recyclerequest",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recyclerequest",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
