# Generated by Django 4.2.13 on 2024-09-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0002_alter_recyclerequest_contact_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecycleRequestStatus",
        ),
    ]
