# Generated by Django 4.2.13 on 2024-09-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0003_delete_recyclerequeststatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecycleRequestStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recycle.recyclerequest",
                    ),
                ),
            ],
        ),
    ]
