# Generated by Django 4.2.13 on 2024-09-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0004_recyclerequeststatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recyclerequeststatus",
            old_name="is_accepted",
            new_name="status",
        ),
    ]
